In [1]:
# o que é uma variável

# texto
variavel_texto = "Frase qualquer"

# numero
variavel_numero = 1

#lista
lista = ["1", "Arroz", "Feijão", 1]
display(lista[0])

'1'

In [3]:
import FundamentalAnalysis as fa

In [4]:
df_summary = fa.summary("mmm")
df_xx = fa.
#balance_sheet_statement
#quote
#enterprise
#available_companies
#profile
#rating
#stock_data_detailed
#stock_data

AttributeError: module 'FundamentalAnalysis' has no attribute 'summary'

In [4]:
import FundamentalAnalysis as fa
import streamlit as st
import matplotlib.pyplot as plt, pandas as pd, numpy as np
from PIL import Image


from matplotlib.pyplot import rc
from pandas_datareader import data as pdr
from datetime import datetime
import yfinance as yf
yf.pdr_override() # <== that's all it takes :-)
from dateutil.parser import parse
from scipy.stats import iqr
from datetime import timedelta, date

In [5]:
def set_pub():
    rc('font', weight='bold')    # bold fonts are easier to see
    rc('grid', c='0.5', ls='-', lw=0.5)
    rc('figure', figsize = (10,8))
    plt.style.use('bmh')
    rc('lines', linewidth=1.3, color='b')

In [7]:
#@st.cache(suppress_st_warning=True)
def summary_stats(ticker):
    #df_summary = fa.summary(ticker)
    df_summary = ticker
    return df_summary

In [2]:
# O que é uma função

print("Uma funcao recebe entradas.")

Uma funcao recebe entradas.

In [3]:
# O que é uma biblioteca
import pandas as pd

In [4]:
# Lendo um arquivo Excel
acoes_ibov = pd.read_excel("IBOV.xlsx")

display(acoes_ibov)

    Código          Ação
0    ABEV3     AMBEV S/A
1    AZUL4          AZUL
2    B3SA3            B3
3    BBAS3        BRASIL
4    BBDC3      BRADESCO
5    BBDC4      BRADESCO
6    BBSE3  BBSEGURIDADE
7   BPAC11    BTGP BANCO
8    BRAP4     BRADESPAR
9    BRDT3  PETROBRAS BR
10   BRFS3        BRF SA
11   BRKM5       BRASKEM
12   BRML3  BR MALLS PAR
13   BTOW3   B2W DIGITAL
14   CCRO3        CCR SA
15   CIEL3         CIELO
16   CMIG4         CEMIG
17   COGN3      COGNA ON
18   CRFB3  CARREFOUR BR
19   CSAN3         COSAN
20   CSNA3  SID NACIONAL
21   CVCB3    CVC BRASIL
22   CYRE3  CYRELA REALT
23   ECOR3   ECORODOVIAS
24   EGIE3  ENGIE BRASIL
25   ELET3    ELETROBRAS
26   ELET6    ELETROBRAS
27   EMBR3       EMBRAER
28   ENBR3   ENERGIAS BR
29   EQTL3    EQUATORIAL
..     ...           ...
43  KLBN11    KLABIN S/A
44   LAME4  LOJAS AMERIC
45   LREN3  LOJAS RENNER
46   MGLU3   MAGAZ LUIZA
47   MRFG3       MARFRIG
48   MRVE3           MRV
49   MULT3     MULTIPLAN
50   NTCO3  GRUPO NATURA
51   PCAR3  P.ACUCAR-CBD
52   PETR3     PETROBRAS
53   PETR4     PETROBRAS
54   QUAL3     QUALICORP
55   RADL3  RAIADROGASIL
56   RAIL3     RUMO S.A.
57   RENT3      LOCALIZA
58  SANB11  SANTANDER BR
59   SBSP3        SABESP
60   SMLS3        SMILES
61  SULA11   SUL AMERICA
62   SUZB3   SUZANO S.A.
63  TAEE11         TAESA
64   TIMP3  TIM PART S/A
65   TOTS3         TOTVS
66   UGPA3      ULTRAPAR
67   USIM5      USIMINAS
68   VALE3          VALE
69   VIVT4  TELEF BRASIL
70   VVAR3     VIAVAREJO
71   WEGE3           WEG
72   YDUQ3    YDUQS PART

[73 rows x 2 columns]

In [5]:
# Acessando página com informações
acao = pd.read_html("https://www.fundamentus.com.br/detalhes.php?papel=TRIS3",
                    decimal=",",
                    thousands=".")
display(acao)
display(acao[0])
display(acao[1])

HTTPError: HTTP Error 403: Forbidden

In [ ]:
# Transpondo as tabelas
acao[0] = acao[0].transpose()
acao[1] = acao[1].transpose()
display(acao[0], acao[1])

In [ ]:
# Separando os grupos de informações sobre a acao para organizar em colunas
# Primeira tabela
informações_1 = acao[0].iloc[:2, :]
informações_2 = acao[0].iloc[2:, :]

# Segunda tabela
informações_3 = acao[1].iloc[:2, :]
informações_4 = acao[1].iloc[2:, :]

display(informações_1 , informações_2, informações_3, informações_4)

In [ ]:
# Concatenando as informações em uma linha única

# Resetando o index para juntar no concatenar
informações_2 = informações_2.reset_index(drop=True) # drop=True remove o index anterior salvo pela função em uma nova coluna
informações_4 = informações_4.reset_index(drop=True) # drop=True remove o index anterior salvo pela função em uma nova coluna

display(informações_1 , informações_2, informações_3, informações_4)

In [ ]:
# Concatenando
acao = pd.concat([informações_1,
                  informações_2,
                  informações_3,
                  informações_4,
                 ], # Quais tabelas quero concatenar em uma só
                 axis=1, # Quero concatenar em colunas
                 join='inner') # Tipo de concatenar inner = o que é comum aos dois 

display(acao)

In [ ]:
# Transforma a primeira linha em cabecalho
acao.columns = acao.iloc[0] # Define o cabeçalho como a primeira linha
acao = acao.drop(0) # Deleta a linha zero, que passou a ser o cabeçalho

display(acao)

In [ ]:
# # Fazendo o programa repetir os passos para diversas acoes

# for codigo_acao in acoes_ibov["Código"]:
#     # Acessando página com informações
        
#     print("Coletando informações do papel:", codigo_acao)
    
#     link_acao = "https://www.fundamentus.com.br/detalhes.php?papel=" + codigo_acao
    
#     acao = pd.read_html(link_acao,
#                         decimal=",",
#                         thousands=".")

#     # Transpondo as tabelas
#     acao[0] = acao[0].transpose()
#     acao[1] = acao[1].transpose()

#     # Separando os grupos de informações sobre a acao para organizar em colunas
#     # Primeira tabela
#     informações_1 = acao[0].iloc[:2, :]
#     informações_2 = acao[0].iloc[2:, :]

#     # Segunda tabela
#     informações_3 = acao[1].iloc[:2, :]
#     informações_4 = acao[1].iloc[2:, :]

#     # Concatenando as informações em uma linha única

#     # Resetando o index para juntar no concatenar
#     informações_2 = informações_2.reset_index(drop=True) # drop=True remove o index anterior salvo pela função em uma nova coluna
#     informações_4 = informações_4.reset_index(drop=True) # drop=True remove o index anterior salvo pela função em uma nova coluna

#     # Concatenando
#     acao = pd.concat([informações_1,
#                       informações_2,
#                       informações_3,
#                       informações_4,
#                      ], # Quais tabelas quero concatenar em uma só
#                      axis=1, # Quero concatenar em colunas
#                      join='inner') # Tipo de concatenar inner = o que é comum aos dois 
    
#     display(acao)

In [ ]:
# Fazendo o programa repetir os passos para diversas acoes
###################################PASSO ADICIONAL PARA CONCATENAR AS INFORMACOES#######################################

# Cria variavel dataframe vazio para consolidar e armazenar as informações em um lugar só
consolidado_acoes = pd.DataFrame()

display(consolidado_acoes)

for codigo_acao in acoes_ibov["Código"]:
    # Acessando página com informações
        
    print("Coletando informações do papel:", codigo_acao)
    
    link_acao = "https://www.fundamentus.com.br/detalhes.php?papel=" + codigo_acao
    
    acao = pd.read_html(link_acao,
                        decimal=",",
                        thousands=".")

    # Transpondo as tabelas
    acao[0] = acao[0].transpose()
    acao[1] = acao[1].transpose()

    # Separando os grupos de informações sobre a acao para organizar em colunas
    # Primeira tabela
    informações_1 = acao[0].iloc[:2, :]
    informações_2 = acao[0].iloc[2:, :]

    # Segunda tabela
    informações_3 = acao[1].iloc[:2, :]
    informações_4 = acao[1].iloc[2:, :]

    # Concatenando as informações em uma linha única

    # Resetando o index para juntar no concatenar
    informações_2 = informações_2.reset_index(drop=True) # drop=True remove o index anterior salvo pela função em uma nova coluna
    informações_4 = informações_4.reset_index(drop=True) # drop=True remove o index anterior salvo pela função em uma nova coluna

    # Concatenando
    acao = pd.concat([informações_1,
                      informações_2,
                      informações_3,
                      informações_4,
                     ], # Quais tabelas quero concatenar em uma só
                     axis=1, # Quero concatenar em colunas
                     join='inner') # Tipo de concatenar inner = o que é comum aos dois 

    # Transforma a primeira linha em cabecalho
    acao.columns = acao.iloc[0] # Define o cabeçalho como a primeira linha
    acao = acao.drop(0) # Deleta a linha zero, que passou a ser o cabeçalho

    # Cria um consolidado com as informações capturadas
    consolidado_acoes = consolidado_acoes.append(acao, sort=False)
    
    # Mostra o robo colocando as informacoes uma a uma na tabela
    # Remover depois
    display(consolidado_acoes)

In [ ]:
display(consolidado_acoes)

In [ ]:
# Correcoes finais no consolidado

# corrigindo index do consolidado
consolidado_acoes = consolidado_acoes.reset_index(drop=True)

display(consolidado_acoes)

# Remove as interrogações do cabeçalho
# acao.columns é uma lista, deve navegar na lista removendo os "?"
novo_cabecalho = [coluna.replace('?', '') for coluna in consolidado_acoes.columns]
consolidado_acoes.columns = novo_cabecalho # Diz que acao.columns agora recebe o novo_cabecalho

# Corrigindo as duas colunas de datas
consolidado_acoes["Data últ cot"] = pd.to_datetime(consolidado_acoes["Data últ cot"],
                                                   errors='ignore',
                                                   format="%d/%m/%Y"
                                                  )

consolidado_acoes["Últ balanço processado"] = pd.to_datetime(consolidado_acoes["Últ balanço processado"],
                                                             errors='ignore',
                                                             format="%d/%m/%Y"
                                                            )

# Corrigindo colunas com valores numéricos
consolidado_acoes["Vol $ méd (2m)"] = pd.to_numeric(consolidado_acoes["Vol $ méd (2m)"],
                                                    errors='coerce'
                                                   )

consolidado_acoes["Valor de mercado"] = pd.to_numeric(consolidado_acoes["Valor de mercado"],
                                                      errors='coerce'
                                                     )

consolidado_acoes["Valor da firma"] = pd.to_numeric(consolidado_acoes["Valor da firma"],
                                                    errors='coerce'
                                                   )

consolidado_acoes["Nro. Ações"] = pd.to_numeric(consolidado_acoes["Nro. Ações"],
                                                errors='coerce'
                                               )

display(consolidado_acoes)

In [ ]:
# Algumas opercações

# Qual a empresa com maior valor de mercado?
display(consolidado_acoes.loc[consolidado_acoes['Valor de mercado'].idxmax()])

# Qual a quantidade de empresas por setor no IBOV?
display(consolidado_acoes.groupby(['Setor']).count()["Papel"])

# Qual o valor de mercado de todas as empresas do IBOV?
print("O valor de mercado do IBOV é:", consolidado_acoes["Valor de mercado"].sum())

# Qual o Vol $ méd (2m) das empresas do IBOV?
vol_med = consolidado_acoes["Vol $ méd (2m)"].mean()
print("O volume médio negociado das empresas do IBOV é :", vol_med)

# Gráfico de volume medio das empresas que possuem volume med acima da médida
%matplotlib inline
# Filtrando empresas com valor de mercado inferior a média
Vol_med_acima_media = consolidado_acoes[consolidado_acoes["Vol $ méd (2m)"] >= vol_med]
# Ordenando a tabela pelo volume medio
Vol_med_acima_media.sort_values(by=['Vol $ méd (2m)'],
                                ascending=True,
                                inplace=True)
display(Vol_med_acima_media)
# Plotando o resultado
Vol_med_acima_media.plot.bar(x="Papel", y="Vol $ méd (2m)")

In [ ]:
# Salvando dados em um excel

consolidado_acoes.to_excel("Ações do IBOV.xlsx",
                           index=False)